-- ═══════════════════════════════════════════════════════════════════════════
-- 0006 — Nazwy boisk (OSM + Mapbox)
-- Kategoria: Boiska  |  Typ: DATA  |  Wymaga: 0002
-- Plik: supabase/migrations/0006_field_names_enriched.sql
-- SQL Editor: 0006 — nazwy boisk (enriched)
-- ═══════════════════════════════════════════════════════════════════════════
-- Uruchamiaj w kolejności numerów. Skrypt idempotentny (bezpieczny ponownie).

update public.fields set name = 'Boisko do koszykówki · ul. Marii Skłodowskiej-Curie 14, Gdynia', updated_at = now() where osm_type = 'node' and osm_id = 5130254522;
update public.fields set name = 'Boisko do koszykówki · ul. Korzenna 2-6b, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 10112395223;
update public.fields set name = 'Boisko do koszykówki · ul. Lubowidzka 8, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 10674884076;
update public.fields set name = 'Boisko do koszykówki · ul. Profesora Romualda Cebertowicza 17, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 10904087187;
update public.fields set name = 'Boisko do koszykówki · ul. Głucha 21a, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 10927544815;
update public.fields set name = 'Boisko do koszykówki · ul. Głucha 21a, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 10927544816;
update public.fields set name = 'Boisko do koszykówki · ul. Karola Kurpińskiego 13, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 11388686968;
update public.fields set name = 'Boisko do koszykówki · ul. Konrada Leczkowa 27, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 11454000409;
update public.fields set name = 'Boisko do koszykówki · ul. Dąbrówki 92, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 11464462663;
update public.fields set name = 'Boisko do koszykówki · ul. Spokojna, Gdynia', updated_at = now() where osm_type = 'node' and osm_id = 11577560910;
update public.fields set name = 'Boisko do koszykówki · ul. Pułkownika Stanisława Dąbka 277, Gdynia', updated_at = now() where osm_type = 'node' and osm_id = 11625055390;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Brzozowa, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 11717236594;
update public.fields set name = 'Boisko do koszykówki · ul. Piekarska 2, Gdynia', updated_at = now() where osm_type = 'node' and osm_id = 12191835741;
update public.fields set name = 'Boisko do koszykówki · ul. Wrzeszczańska Droga Wzgórz, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 12624297516;
update public.fields set name = 'Boisko do koszykówki · ul. Nadwiślańska 24, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 12682615469;
update public.fields set name = 'Boisko do koszykówki · ul. Jęczmienna 14, Gdynia', updated_at = now() where osm_type = 'node' and osm_id = 12856322352;
update public.fields set name = 'Boisko do koszykówki · ul. Stolarzy, Gdańsk', updated_at = now() where osm_type = 'node' and osm_id = 13302145788;
update public.fields set name = 'Boisko do koszykówki · ul. Tytusa Chałubińskiego 37, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 60235402;
update public.fields set name = 'Boisko do koszykówki · ul. Gospody 10, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 102696942;
update public.fields set name = 'Boisko do koszykówki · ul. Jaśkowa Dolina 89, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 132639854;
update public.fields set name = 'Boisko do koszykówki · ul. Bitwy Oliwskiej 20, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 142157470;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Niepodległości 751, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 142660278;
update public.fields set name = 'Boisko do koszykówki · ul. Działdowska 19a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 149554290;
update public.fields set name = 'Boisko do koszykówki · ul. Wileńska 57b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 149762621;
update public.fields set name = 'Boisko do koszykówki · ul. Wielkopolska 20, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 150731065;
update public.fields set name = 'Boisko do koszykówki · ul. Aleksandra Dulina 1, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 153503765;
update public.fields set name = 'Boisko do koszykówki · ul. Człuchowska 6, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 155249959;
update public.fields set name = 'Boisko do koszykówki · ul. Zbożowa 25, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 156869084;
update public.fields set name = 'Boisko do koszykówki · ul. Kcyńska 6h, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 156869086;
update public.fields set name = 'Boisko do koszykówki · ul. Szubińska 17, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 156869087;
update public.fields set name = 'Boisko do koszykówki · ul. Jana Komierowskiego, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 157030181;
update public.fields set name = 'Boisko do koszykówki · ul. Morska 224, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 157030182;
update public.fields set name = 'Boisko do koszykówki · ul. Chylońska 137e, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 157030184;
update public.fields set name = 'Boisko do koszykówki · ul. Owsiana 7, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 157030186;
update public.fields set name = 'Boisko do koszykówki · ul. Wejherowska 55, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 157030193;
update public.fields set name = 'Boisko do koszykówki · ul. Borowikowa 1, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 157030199;
update public.fields set name = 'Boisko do koszykówki · ul. Częstochowska 30, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 160868154;
update public.fields set name = 'Boisko do koszykówki · ul. Ogrodowa 26, Leźno', updated_at = now() where osm_type = 'way' and osm_id = 161278335;
update public.fields set name = 'Boisko do koszykówki · ul. Sucha 29, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 161313180;
update public.fields set name = 'Boisko do koszykówki · ul. Generał Marii Wittekówny 14, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 162214276;
update public.fields set name = 'Boisko do koszykówki · ul. Macieja Kamieńskiego 5f, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 163696161;
update public.fields set name = 'Boisko do koszykówki · ul. Platynowa 24a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 163931553;
update public.fields set name = 'Boisko do koszykówki · ul. Stanisława Hebanowskiego 85c, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 164326428;
update public.fields set name = 'Boisko do koszykówki · ul. Janusza Kusocińskiego 3, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 165358171;
update public.fields set name = 'Boisko do koszykówki · ul. Pułkownika Stanisława Dąbka 63, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165599247;
update public.fields set name = 'Boisko do koszykówki · ul. Majora Henryka Sucharskiego 15a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165664932;
update public.fields set name = 'Boisko do koszykówki · ul. Majora Henryka Sucharskiego 2, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165664934;
update public.fields set name = 'Boisko do koszykówki · ul. Wielkokacka 18, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165702730;
update public.fields set name = 'Boisko do koszykówki · ul. Stawna 4, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165702732;
update public.fields set name = 'Boisko do koszykówki · ul. Żeglarzy 9, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165710062;
update public.fields set name = 'Boisko do koszykówki · ul. Króla Jana III 20a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165713601;
update public.fields set name = 'Boisko do koszykówki · ul. Olchowa 4, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165716205;
update public.fields set name = 'Boisko do koszykówki · ul. Pułkownika Stanisława Dąbka 257c, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165726870;
update public.fields set name = 'Boisko do koszykówki · ul. Legionów 16, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165729603;
update public.fields set name = 'Boisko do koszykówki · ul. Halicka 6, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165751507;
update public.fields set name = 'Boisko do koszykówki · ul. Halicka 6, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165751934;
update public.fields set name = 'Boisko do koszykówki · ul. Chwarznieńska, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165753541;
update public.fields set name = 'Boisko do koszykówki · ul. Władysława Syrokomli 17a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165754338;
update public.fields set name = 'Boisko do koszykówki · ul. Mikołaja Reja 4, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165754340;
update public.fields set name = 'Boisko do koszykówki · ul. Jana z Kolna 11, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 165779237;
update public.fields set name = 'Boisko do koszykówki · ul. Do Studzienki 49, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 166824786;
update public.fields set name = 'Boisko do koszykówki · ul. Morska 192, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 167160128;
update public.fields set name = 'Boisko do koszykówki · ul. Tatrzańska 22, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 167360753;
update public.fields set name = 'Boisko do koszykówki · ul. Nowiec 20, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 167393900;
update public.fields set name = 'Boisko do koszykówki · ul. Nowiec 40, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 167393901;
update public.fields set name = 'Boisko do koszykówki · ul. Dolne Młyny 17d, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 167401924;
update public.fields set name = 'Boisko do koszykówki · ul. Kazimierza Przerwy-Tetmajera 65a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 167736458;
update public.fields set name = 'Boisko do koszykówki · ul. Źródło Marii 50, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 168470313;
update public.fields set name = 'Boisko do koszykówki · ul. Krzemowa 4, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 168750874;
update public.fields set name = 'Boisko do koszykówki · ul. Do Studzienki 32, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 169395386;
update public.fields set name = 'Boisko do koszykówki · ul. Adama Mickiewicza 14, Chwaszczyno', updated_at = now() where osm_type = 'way' and osm_id = 171038395;
update public.fields set name = 'Boisko do koszykówki · ul. Leopolda Staffa 24, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 173122141;
update public.fields set name = 'Boisko do koszykówki · ul. Promienista 5, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 173596402;
update public.fields set name = 'Boisko do koszykówki · ul. Stogi 20, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 173621604;
update public.fields set name = 'Boisko do koszykówki · ul. Stogi 20, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 173621605;
update public.fields set name = 'Boisko do koszykówki · ul. Ryszarda Wagnera 40a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 176209746;
update public.fields set name = 'Boisko do koszykówki · ul. Brzozowa 2, Otomin', updated_at = now() where osm_type = 'way' and osm_id = 176818816;
update public.fields set name = 'Boisko do koszykówki · ul. Marcina Dragana 2, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 177328755;
update public.fields set name = 'Boisko do koszykówki · ul. Głęboka 11, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 179019210;
update public.fields set name = 'Boisko do koszykówki · ul. Macieja Kamieńskiego 5d, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 179749652;
update public.fields set name = 'Boisko do koszykówki · ul. Piotra Czajkowskiego 5, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 179749653;
update public.fields set name = 'Boisko do koszykówki · ul. Kolonia Zręby 79, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 179749658;
update public.fields set name = 'Boisko do koszykówki · ul. Legionów 23a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 179751358;
update public.fields set name = 'Boisko do koszykówki · ul. Marszałka Ferdynanda Focha 18, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 179772243;
update public.fields set name = 'Boisko do koszykówki · ul. Księdza Leona Miszewskiego 12, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 179801663;
update public.fields set name = 'Boisko do koszykówki · ul. Ludwika Zamenhofa 4a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 180843726;
update public.fields set name = 'Boisko do koszykówki · ul. Kaczeńcowa 12, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 181590608;
update public.fields set name = 'Boisko do koszykówki · ul. Sokola 2a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 181861865;
update public.fields set name = 'Boisko do koszykówki · ul. Wieluńska 86, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 182072765;
update public.fields set name = 'Boisko do koszykówki · ul. Wolności 25, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 182242385;
update public.fields set name = 'Boisko do koszykówki · ul. Aksamitna 8, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 182602382;
update public.fields set name = 'Boisko do koszykówki · ul. Adama Asnyka, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 183053055;
update public.fields set name = 'Boisko do koszykówki · ul. Jagiellońska 40a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 183361694;
update public.fields set name = 'Boisko do koszykówki · ul. Obywatelska 1, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 183639534;
update public.fields set name = 'Boisko do koszykówki · ul. Wincentego Witosa 15, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 183639536;
update public.fields set name = 'Boisko do koszykówki · ul. Wincentego Witosa 15, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 183639539;
update public.fields set name = 'Boisko do koszykówki · ul. Orłowska 13, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 183641456;
update public.fields set name = 'Boisko do koszykówki · ul. Zielony Trójkąt 29, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 184388405;
update public.fields set name = 'Boisko do koszykówki · ul. Niska 4, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 184745152;
update public.fields set name = 'Boisko do koszykówki · ul. Józefa Kotarbińskiego 23, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 185832784;
update public.fields set name = 'Boisko do koszykówki · ul. Kasztanowa 7e, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 185836223;
update public.fields set name = 'Boisko do koszykówki · ul. Podgórna 5, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 188365996;
update public.fields set name = 'Boisko do koszykówki · ul. Niedźwiednik 36a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 199658757;
update public.fields set name = 'Boisko do koszykówki · ul. Szafranowa 33c, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 200742833;
update public.fields set name = 'Boisko do koszykówki · ul. Szczecińska 16, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 202061084;
update public.fields set name = 'Boisko do koszykówki · ul. Szczecińska 18, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 202061085;
update public.fields set name = 'Boisko do koszykówki · ul. Bolesława Chrobrego 15, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 202236681;
update public.fields set name = 'Boisko do koszykówki · ul. Włóczników 6, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 202236683;
update public.fields set name = 'Boisko do koszykówki · ul. Bolesława Chrobrego 11a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 202236684;
update public.fields set name = 'Boisko do koszykówki · ul. Kaszubska 8a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 204526242;
update public.fields set name = 'Boisko do koszykówki · ul. Arenda Dickmana 15, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 205507469;
update public.fields set name = 'Boisko do koszykówki · ul. Jana Kochanowskiego 25a, Suchy Dwór', updated_at = now() where osm_type = 'way' and osm_id = 206063911;
update public.fields set name = 'Boisko do koszykówki · ul. Bernarda Chrzanowskiego 84, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 208560973;
update public.fields set name = 'Boisko do koszykówki · ul. Świętopełka 24, Rumia', updated_at = now() where osm_type = 'way' and osm_id = 210293675;
update public.fields set name = 'Decathlon · ul. Szczęśliwa 1, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 222849415;
update public.fields set name = 'Boisko do koszykówki · ul. podpułkownika Ignacego Szpunara 8c, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 224720273;
update public.fields set name = 'Boisko do koszykówki · ul. Kartuska 243a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 224914227;
update public.fields set name = 'Boisko do koszykówki · ul. Oskara Kolberga 24, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 227101009;
update public.fields set name = 'Boisko do koszykówki · ul. Władysława Cieszyńskiego 10, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 227101010;
update public.fields set name = 'Boisko do koszykówki · ul. Stefana Okrzei 13, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 227186701;
update public.fields set name = 'Boisko do koszykówki · ul. Wojewódzka 36, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 234790417;
update public.fields set name = 'Boisko do koszykówki · ul. Generała Józefa Hallera 8, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 234790431;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Jana Pawła II 25b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 236511475;
update public.fields set name = 'Boisko do koszykówki · ul. Polanki 94a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 237030383;
update public.fields set name = 'Boisko do koszykówki · ul. Tadeusza Kościuszki 10b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 237289656;
update public.fields set name = 'Boisko do koszykówki · ul. Startowa 21a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 238121161;
update public.fields set name = 'Boisko do koszykówki · ul. Pilotów 8e, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 238121167;
update public.fields set name = 'Boisko do koszykówki · ul. Roślinna 11a, Dębogórze', updated_at = now() where osm_type = 'way' and osm_id = 238255319;
update public.fields set name = 'Boisko do koszykówki · ul. Kołobrzeska 77, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 238829257;
update public.fields set name = 'Boisko do koszykówki · ul. Kołobrzeska 75, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 238829476;
update public.fields set name = 'Boisko do koszykówki · ul. Jagiellońska 26e, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 238977865;
update public.fields set name = 'Boisko do koszykówki · ul. Obrońców Wybrzeża 5a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 238977868;
update public.fields set name = 'Boisko do koszykówki · ul. Kołobrzeska 42b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 239155578;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Legionów 13, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 239538044;
update public.fields set name = 'Boisko do koszykówki · ul. Jodłowa 4a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 243452783;
update public.fields set name = 'Boisko do koszykówki · ul. Kłosowa 3, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 243452786;
update public.fields set name = 'Boisko do koszykówki · ul. Mariana Smoluchowskiego 11, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 244860484;
update public.fields set name = 'Boisko do koszykówki · ul. Gryfa Pomorskiego 52b, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 255936220;
update public.fields set name = 'Boisko do koszykówki · ul. Różana 4, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 256015723;
update public.fields set name = 'Boisko do koszykówki · ul. Tobiasza 7, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 256015725;
update public.fields set name = 'Boisko do koszykówki · ul. Tęczowa 32, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 256552372;
update public.fields set name = 'Boisko do koszykówki · ul. Chylońska 218, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 256821333;
update public.fields set name = 'Boisko do koszykówki · ul. Ofiar Piaśnicy, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 260663455;
update public.fields set name = 'Boisko do koszykówki · ul. Czesława Miłosza 4, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 263467362;
update public.fields set name = 'Boisko do koszykówki · ul. Mikołaja Kopernika 90, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 263468173;
update public.fields set name = 'Boisko do koszykówki · ul. Morelowa 19, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 278169432;
update public.fields set name = 'Boisko do koszykówki · ul. Pomorska 13b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 279946198;
update public.fields set name = 'Boisko do koszykówki · ul. Kaszubska Droga 25e, Chwaszczyno', updated_at = now() where osm_type = 'way' and osm_id = 292878405;
update public.fields set name = 'Boisko do koszykówki · ul. Ignacego Matuszewskiego 11, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 293082313;
update public.fields set name = 'Boisko do koszykówki · ul. Kartuska 128, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 293133875;
update public.fields set name = 'Boisko do koszykówki · ul. Jacka Malczewskiego 84, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 293133879;
update public.fields set name = 'Boisko do koszykówki · ul. Związku Jaszczurczego 4, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 293197342;
update public.fields set name = 'Boisko do koszykówki · ul. Lecha Bądkowskiego 32, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 293413311;
update public.fields set name = 'Boisko do koszykówki · ul. Antoniego Suchanka 4, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 294003124;
update public.fields set name = 'Boisko do koszykówki · ul. Marcina Dragana 21, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 294602936;
update public.fields set name = 'Boisko do koszykówki · ul. Kamienna Grobla 13, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 299619903;
update public.fields set name = 'Boisko do koszykówki · ul. Paprykowa 30a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 299863656;
update public.fields set name = 'Boisko do koszykówki · ul. Agrarna 2, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 303834433;
update public.fields set name = 'Boisko do koszykówki · ul. Władysława IV 54, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 304488051;
update public.fields set name = 'Boisko do koszykówki · ul. Władysława IV 54, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 304488052;
update public.fields set name = 'Boisko do koszykówki · ul. Władysława IV 54, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 304488053;
update public.fields set name = 'Boisko do koszykówki · ul. Jana Pestalozziego 11/13, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 311812100;
update public.fields set name = 'Boisko do koszykówki · ul. Pomorska 18g, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 337071967;
update public.fields set name = 'Boisko do koszykówki · ul. Wolności 22b, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 350316400;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Grunwaldzka 244a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 354197301;
update public.fields set name = 'Boisko do koszykówki · ul. Cygańska Góra 18d, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 363366222;
update public.fields set name = 'Boisko do koszykówki · ul. Partyzantów 25, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 363550392;
update public.fields set name = 'Boisko do koszykówki · ul. Czesława Miłosza 39, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 367717896;
update public.fields set name = 'Boisko do koszykówki · ul. Klonowa 20, Banino', updated_at = now() where osm_type = 'way' and osm_id = 368437085;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Grunwaldzka 238, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 374525048;
update public.fields set name = 'Boisko do koszykówki · ul. Tysiąclecia 5, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 381585372;
update public.fields set name = 'Boisko do koszykówki · ul. Klasyczna 4, Borkowo', updated_at = now() where osm_type = 'way' and osm_id = 388665194;
update public.fields set name = 'Boisko do koszykówki · ul. Gospody 35, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 397440124;
update public.fields set name = 'Boisko do koszykówki · ul. Leopolda Staffa 11f, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 398559394;
update public.fields set name = 'Boisko do koszykówki · ul. Leopolda Staffa 11f, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 398559395;
update public.fields set name = 'Boisko do koszykówki · ul. Armii Krajowej 151, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 401564325;
update public.fields set name = 'Boisko do koszykówki · ul. Jagiellońska 5, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 401574242;
update public.fields set name = 'Boisko do koszykówki · ul. Chwarznieńska 93, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 404975078;
update public.fields set name = 'Boisko do koszykówki · ul. Królewskie Wzgórze 7, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 406480492;
update public.fields set name = 'Boisko do koszykówki · ul. Krowoderska 11b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 411348530;
update public.fields set name = 'Boisko do koszykówki · ul. Kolorowa 3, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 413038225;
update public.fields set name = 'Boisko do koszykówki · ul. Reformacka 22, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 417698381;
update public.fields set name = 'Boisko do koszykówki · ul. 23 Marca 78a, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 428425501;
update public.fields set name = 'Boisko do koszykówki · ul. Władysława Broniewskiego 12, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 430896241;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Niepodległości 732a, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 430954968;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Niepodległości 738b, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 430954969;
update public.fields set name = 'Boisko do koszykówki · ul. Pułkownika Stanisława Dąbka 203b, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 431119776;
update public.fields set name = 'Boisko do koszykówki · ul. Leopolda Stokowskiego 1c, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 431511296;
update public.fields set name = 'Boisko do koszykówki · ul. 3 Maja 31b, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 431870751;
update public.fields set name = 'Boisko do koszykówki · ul. 3 Maja 31b, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 431870758;
update public.fields set name = 'Boisko do koszykówki · ul. Morska 301, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 435110704;
update public.fields set name = 'Boisko do koszykówki · ul. Franciszka Sędzickiego 24, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 435137186;
update public.fields set name = 'Boisko do koszykówki · ul. Wyzwolenia 21, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 435824396;
update public.fields set name = 'Boisko do koszykówki · ul. Jagiellońska 14, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 436937930;
update public.fields set name = 'Boisko do koszykówki · ul. Grabowo 11, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 437242913;
update public.fields set name = 'Boisko do koszykówki · ul. Władysława IV 53, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 439451350;
update public.fields set name = 'Boisko do koszykówki · ul. Chabrowa 43, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 440381679;
update public.fields set name = 'Boisko do koszykówki · ul. Leśna Góra 5a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 440518369;
update public.fields set name = 'Boisko do koszykówki · ul. Mikołaja Kopernika 32, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 441132099;
update public.fields set name = 'Boisko do koszykówki · ul. Partyzantów 22, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 441820218;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Marszałka Józefa Piłsudskiego 18, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 441820219;
update public.fields set name = 'Boisko do koszykówki · ul. Wilanowska 7, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 446839795;
update public.fields set name = 'Boisko do koszykówki · ul. Diany 30a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 496022524;
update public.fields set name = 'Boisko do koszykówki · ul. Tarnowska 1c, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 496858210;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Jana Pawła II 1b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 499119195;
update public.fields set name = 'Boisko do koszykówki · ul. Lubczykowa 5, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 502487053;
update public.fields set name = 'Boisko do koszykówki · ul. Dywizjonu 303 9c, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 508640617;
update public.fields set name = 'Boisko do koszykówki · ul. Stanisława Skarżyńskiego 6c, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 508647014;
update public.fields set name = 'Boisko do koszykówki · ul. Jaśkowa Dolina 79, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 511549334;
update public.fields set name = 'Boisko do koszykówki · ul. Stefana Żeromskiego 9, Kosakowo', updated_at = now() where osm_type = 'way' and osm_id = 513176541;
update public.fields set name = 'Boisko do koszykówki · ul. Pilotów 9a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 513230511;
update public.fields set name = 'Boisko do koszykówki · ul. Głucha 21a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 515011695;
update public.fields set name = 'Boisko do koszykówki · ul. Daliowa 11b, Kosakowo', updated_at = now() where osm_type = 'way' and osm_id = 515688444;
update public.fields set name = 'Boisko do koszykówki · ul. kontradmirała Włodzimierza Brunona Steyera 9c, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 515932262;
update public.fields set name = 'Boisko do koszykówki · ul. Raduńska 19, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 516866634;
update public.fields set name = 'Boisko do koszykówki · ul. Związkowa 8, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 516915077;
update public.fields set name = 'Boisko do koszykówki · ul. Ubocze 28, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 516915642;
update public.fields set name = 'Boisko do koszykówki · ul. Grabowa 7, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 517064356;
update public.fields set name = 'Boisko do koszykówki · ul. Piotra Michałowskiego 50, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 522188934;
update public.fields set name = 'Boisko do koszykówki · ul. Goplańska 3e, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 522799344;
update public.fields set name = 'Boisko do koszykówki · ul. Admirała Józefa Unruga 88a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 524844348;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Niepodległości 751, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 525360856;
update public.fields set name = 'Boisko do koszykówki · ul. Lipnicka Droga, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 527263145;
update public.fields set name = 'Boisko do koszykówki · ul. Grabowa 7, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 528940936;
update public.fields set name = 'V Liceum Ogólnokształcące im. Stefana Żeromskiego · ul. Alfa Liczmańskiego 23, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 536343259;
update public.fields set name = 'V Liceum Ogólnokształcące im. Stefana Żeromskiego · ul. Alfa Liczmańskiego 24/25, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 536343260;
update public.fields set name = 'Boisko do koszykówki · ul. Krakowska 10, Rumia', updated_at = now() where osm_type = 'way' and osm_id = 544163104;
update public.fields set name = 'Boisko do koszykówki · ul. Gdańska 28, Rumia', updated_at = now() where osm_type = 'way' and osm_id = 544164787;
update public.fields set name = 'Boisko do koszykówki · ul. Stoczniowców 13, Rumia', updated_at = now() where osm_type = 'way' and osm_id = 544165981;
update public.fields set name = 'Boisko do koszykówki · ul. Robotnicza 15, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 548613025;
update public.fields set name = 'Boisko do koszykówki · ul. Feniksa 4, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 551970470;
update public.fields set name = 'Boisko do koszykówki · ul. Kołobrzeska 51e, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 562007439;
update public.fields set name = 'Boisko do koszykówki · ul. Dębogórska 28, Dębogórze-Wybudowanie', updated_at = now() where osm_type = 'way' and osm_id = 562233597;
update public.fields set name = 'Boisko do koszykówki · ul. Henryka Dąbrowskiego 141a, Rumia', updated_at = now() where osm_type = 'way' and osm_id = 582457082;
update public.fields set name = 'Boisko do koszykówki · ul. Maryli 26, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 588398796;
update public.fields set name = 'Boisko do koszykówki · ul. Juliusza Słowackiego 196, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 588781636;
update public.fields set name = 'Boisko do koszykówki · ul. Witomińska 25/27, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 589063940;
update public.fields set name = 'Boisko do koszykówki · ul. Lawendowe Wzgórze 5, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 589520160;
update public.fields set name = 'Boisko do koszykówki · ul. Wiczlińska 93, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 589685207;
update public.fields set name = 'Boisko do koszykówki · ul. Żabi Kruk 5, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 620184257;
update public.fields set name = 'Boisko do koszykówki · ul. Stanisława Wąsowicza 30, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 629927927;
update public.fields set name = 'Boisko do koszykówki · ul. Ciesielska 7, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 630361047;
update public.fields set name = 'Boisko do koszykówki · ul. Benisławskiego 20, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 635445588;
update public.fields set name = 'Boisko do koszykówki · ul. Jesionowa 8, Przejazdowo', updated_at = now() where osm_type = 'way' and osm_id = 643374233;
update public.fields set name = 'Boisko do koszykówki · ul. Krosna 17, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 643376663;
update public.fields set name = 'Boisko do koszykówki · ul. Tytusa Chałubińskiego 12, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 644526003;
update public.fields set name = 'Boisko do koszykówki · ul. Nabrzeże Ziółkowskiego, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 669471680;
update public.fields set name = 'Boisko do koszykówki · ul. Skarpowa 70, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 687246619;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Wojska Polskiego, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 697088826;
update public.fields set name = 'Boisko do koszykówki · ul. Szymona Czechowicza 1, Pogórze', updated_at = now() where osm_type = 'way' and osm_id = 697457486;
update public.fields set name = 'Boisko do koszykówki · ul. Leśna Góra 8, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 697762234;
update public.fields set name = 'Boisko do koszykówki · ul. Leszczynowa 48f, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 699127863;
update public.fields set name = 'Boisko do koszykówki · ul. Klimatyczna 88e, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 702546142;
update public.fields set name = 'Boisko do koszykówki · ul. Franciszka Bohomolca 3e, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 703191839;
update public.fields set name = 'Boisko do koszykówki · ul. Otomińska 80, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 703202558;
update public.fields set name = 'Boisko do koszykówki · ul. Tartaczna 2, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 705103649;
update public.fields set name = 'Boisko do koszykówki · ul. Sówki 12, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 711951413;
update public.fields set name = 'Boisko do koszykówki · ul. Heliosa 14, Kowale', updated_at = now() where osm_type = 'way' and osm_id = 717147807;
update public.fields set name = 'Boisko do koszykówki · ul. Wczasy 3, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 720897880;
update public.fields set name = 'Boisko do koszykówki · ul. Elbląska 54/60, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 733749990;
update public.fields set name = 'Boisko do koszykówki · ul. Rogalińska 17, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 736826311;
update public.fields set name = 'Boisko do koszykówki · ul. 23 Marca 91d, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 778341627;
update public.fields set name = 'Boisko do koszykówki · ul. Błękitna 1a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 783728783;
update public.fields set name = 'Boisko do koszykówki · ul. Dębowa 5, Wiślinka', updated_at = now() where osm_type = 'way' and osm_id = 793306780;
update public.fields set name = 'Boisko do koszykówki · ul. Srebrniki 10, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 806957453;
update public.fields set name = 'Boisko do koszykówki · ul. Topolowa 7, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 809936182;
update public.fields set name = 'Boisko do koszykówki · ul. Jana III Sobieskiego 63, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 815453204;
update public.fields set name = 'Boisko do koszykówki · ul. Spokojna 30, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 821485669;
update public.fields set name = 'Boisko do koszykówki · ul. Opolska 7a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 824120433;
update public.fields set name = 'Boisko do koszykówki · ul. Narcyzowa 8c, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 824766953;
update public.fields set name = 'Boisko do koszykówki · ul. Uczniowska 2, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 824786673;
update public.fields set name = 'Boisko do koszykówki · ul. Jana Sobieskiego 96, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 826506721;
update public.fields set name = 'Boisko do koszykówki · ul. Konrada Guderskiego 26a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 827142422;
update public.fields set name = 'Boisko do koszykówki · ul. Zbożowa 9, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 828444416;
update public.fields set name = 'Boisko do koszykówki · ul. Tadeusza Jasińskiego 65, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 850596895;
update public.fields set name = 'Boisko do koszykówki · ul. Augustowska, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 870770066;
update public.fields set name = 'Boisko do koszykówki · ul. Inżyniera Jana Śmidowicza 73, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 892204220;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Jana Pawła II 3, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 922450960;
update public.fields set name = 'Boisko do koszykówki · ul. Polanki 66, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 941649759;
update public.fields set name = 'Boisko do koszykówki · ul. Polanki 66, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 941649760;
update public.fields set name = 'Boisko do koszykówki · ul. Polanki 122, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 943310797;
update public.fields set name = 'Boisko do koszykówki · ul. Książąt Pomorskich 16-18, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 947769348;
update public.fields set name = 'Boisko do koszykówki · ul. Przyokopowa 10b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 948145465;
update public.fields set name = 'Boisko do koszykówki · ul. Spacerowa 16b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 951992021;
update public.fields set name = 'Boisko do koszykówki · ul. Józefa Czyżewskiego 14, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 953803516;
update public.fields set name = 'Boisko do koszykówki · ul. 3 Maja 17b, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 953976336;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Legionów 44, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 953983226;
update public.fields set name = 'Boisko do koszykówki · ul. Kameralna 6, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 954181453;
update public.fields set name = 'Boisko do koszykówki · ul. Raduńska 64, Niestępowo', updated_at = now() where osm_type = 'way' and osm_id = 958242440;
update public.fields set name = 'Boisko do koszykówki · ul. Jana Kanapariusza, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 975833127;
update public.fields set name = 'Boisko do koszykówki · ul. Majora Mieczysława Słabego 4, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 980374469;
update public.fields set name = 'Boisko do koszykówki · ul. Piastowska 106b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 981355536;
update public.fields set name = 'Boisko do koszykówki · ul. Obrońców Wybrzeża 8d, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 981355550;
update public.fields set name = 'Boisko do koszykówki · ul. Józefa Czyżewskiego 31b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 984957960;
update public.fields set name = 'Boisko do koszykówki', updated_at = now() where osm_type = 'way' and osm_id = 987741304;
update public.fields set name = 'Boisko do koszykówki · ul. Macieja Kamieńskiego 5f, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 998045785;
update public.fields set name = 'Boisko do koszykówki · ul. Osiek 18, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1007800789;
update public.fields set name = 'Boisko do koszykówki · ul. Siostry Faustyny 4d, Kowale', updated_at = now() where osm_type = 'way' and osm_id = 1008646266;
update public.fields set name = 'Boisko do koszykówki · ul. Stefana Czarnieckiego 14c, Pogórze', updated_at = now() where osm_type = 'way' and osm_id = 1008998855;
update public.fields set name = 'Boisko do koszykówki · ul. Ludwika Waryńskiego 36a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1013360805;
update public.fields set name = 'Boisko do koszykówki · ul. Inżyniera Jana Śmidowicza 47, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1016427640;
update public.fields set name = 'Boisko do koszykówki · ul. Głuszca 9, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1044813393;
update public.fields set name = 'Boisko do koszykówki · ul. Modra 2, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1049624265;
update public.fields set name = 'Boisko do koszykówki · ul. Starowiejska 3, Kowale', updated_at = now() where osm_type = 'way' and osm_id = 1059303990;
update public.fields set name = 'Boisko do koszykówki · ul. Subisława 31b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1059410267;
update public.fields set name = 'Boisko do koszykówki · ul. Dywizjonu 303 27, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1065704183;
update public.fields set name = 'Boisko do koszykówki · ul. Bitwy pod Płowcami 58a, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 1066522767;
update public.fields set name = 'Boisko do koszykówki · ul. Obrońców Wybrzeża 3c, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1071112136;
update public.fields set name = 'Boisko do koszykówki · ul. Kombatantów 1a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1072070453;
update public.fields set name = 'Boisko do koszykówki · ul. Janusza Meissnera 11, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1073641859;
update public.fields set name = 'Boisko do koszykówki · ul. Janusza Meissnera 11, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1073641860;
update public.fields set name = 'Boisko do koszykówki · ul. Arenda Dickmana 14a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1077221328;
update public.fields set name = 'Boisko do koszykówki · ul. Wrzosy 28c, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1080158289;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Generała Józefa Hallera 247c, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1080428627;
update public.fields set name = 'Boisko do koszykówki · ul. Pilotów 16a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1081078319;
update public.fields set name = 'Boisko do koszykówki · ul. Ferdynanda Magellana 6a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1087772411;
update public.fields set name = 'Boisko do koszykówki · ul. Na Stoku 38, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1088322913;
update public.fields set name = 'Boisko do koszykówki · ul. Emilii Plater 8, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 1091116973;
update public.fields set name = 'Boisko do koszykówki · ul. Wolności 24, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1095097414;
update public.fields set name = 'Boisko do koszykówki · ul. Fabryczna, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1095375062;
update public.fields set name = 'Boisko do koszykówki · ul. Wajdeloty 13, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1097136965;
update public.fields set name = 'Boisko do koszykówki · ul. Generała Tadeusza Bora-Komorowskiego 86b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1101318921;
update public.fields set name = 'Boisko do koszykówki · ul. Bronisława Dembińskiego 41, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1103288562;
update public.fields set name = 'Boisko do koszykówki · ul. Stefana Okrzei 6, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1107577215;
update public.fields set name = 'Boisko do koszykówki · ul. Romana Wyrobka 11, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1111779887;
update public.fields set name = 'Boisko do koszykówki · ul. Gabriela Rzączyńskiego 1, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1119496058;
update public.fields set name = 'Boisko do koszykówki · ul. Franciszka Zabłockiego 3a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1131823513;
update public.fields set name = 'Boisko do koszykówki · ul. Tadeusza Kościuszki 154, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1135284733;
update public.fields set name = 'Boisko do koszykówki · ul. Siennicka 23, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1136797476;
update public.fields set name = 'Boisko do koszykówki · ul. 1 Maja 20, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 1144485667;
update public.fields set name = 'Boisko do koszykówki · ul. Tarasy 10, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1151176127;
update public.fields set name = 'Boisko do koszykówki · ul. Grzegorza Piramowicza 1/2, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1162939338;
update public.fields set name = 'Boisko do koszykówki · ul. Chylońska 216, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1174584380;
update public.fields set name = 'Boisko do koszykówki · ul. Podchorążych 16, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1174783247;
update public.fields set name = 'Boisko do koszykówki · ul. Bursztynowa 1b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1180485256;
update public.fields set name = 'Boisko do koszykówki · ul. Tatrzańska 40, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1180530818;
update public.fields set name = 'Boisko do koszykówki · ul. Wacława Balcerskiego 18c, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1186544603;
update public.fields set name = 'Boisko do koszykówki · ul. Pomorska 90b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1187896129;
update public.fields set name = 'Boisko do koszykówki · ul. Bohaterów Starówki Warszawskiej 10a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1194528402;
update public.fields set name = 'Boisko do koszykówki · ul. Leona Droszyńskiego 24, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1194875199;
update public.fields set name = 'Boisko do koszykówki · ul. Wiosenna 57, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1198828509;
update public.fields set name = 'Boisko do koszykówki · ul. Pułkownika Aleksandra Wilka-Krzyżanowskiego 6, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1201566680;
update public.fields set name = 'Boisko do koszykówki · ul. Bulońska 30, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1201567732;
update public.fields set name = 'Boisko do koszykówki · ul. Pomorska 60, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1202939081;
update public.fields set name = 'Boisko do koszykówki · ul. Mieszka I 7, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 1204302114;
update public.fields set name = 'Boisko do koszykówki · ul. Polskiego Czerwonego Krzyża 3a, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1205095495;
update public.fields set name = 'Boisko do koszykówki · ul. Pionierów 6, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1205364639;
update public.fields set name = 'Boisko do koszykówki · ul. Orłowska 21, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1224503379;
update public.fields set name = 'Boisko do koszykówki · ul. Ikara 3, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1225282134;
update public.fields set name = 'Boisko do koszykówki · ul. Ludwika Beethovena 8b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1228118202;
update public.fields set name = 'Boisko do koszykówki · ul. Żeglarska 3d, Borkowo', updated_at = now() where osm_type = 'way' and osm_id = 1233595722;
update public.fields set name = 'Boisko do koszykówki · ul. Sienna 11k, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1235349390;
update public.fields set name = 'Boisko do koszykówki · ul. Sienna 11k, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1235349391;
update public.fields set name = 'Boisko do koszykówki · ul. Gostyńska 72, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1240454735;
update public.fields set name = 'Boisko do koszykówki · ul. Gospody 15a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1242184833;
update public.fields set name = 'Boisko do koszykówki · ul. Władysława Syrokomli 6, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 1242259442;
update public.fields set name = 'Boisko do koszykówki · ul. Majora Mieczysława Słabego 14, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1243433981;
update public.fields set name = 'Boisko do koszykówki · ul. Zbigniewa Podleckiego 15, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1265381176;
update public.fields set name = 'Boisko do koszykówki · ul. Janiny Porazińskiej 12, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1268857346;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Grunwaldzka 609a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1271835382;
update public.fields set name = 'Boisko do koszykówki · ul. Wyzwolenia 5a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1272119028;
update public.fields set name = 'Boisko do koszykówki · ul. Miodowa 13, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1272623616;
update public.fields set name = 'Boisko do koszykówki · ul. Azymutalna 11, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1278538815;
update public.fields set name = 'Boisko do koszykówki · ul. Taneczna 11, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1299372250;
update public.fields set name = 'Boisko do koszykówki · ul. Władysława Jagiełły 22, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1303352021;
update public.fields set name = 'Boisko do koszykówki · ul. Dworska 29a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1309966163;
update public.fields set name = 'Boisko do koszykówki · ul. Tatrzańska 21, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1314195069;
update public.fields set name = 'Boisko do koszykówki · ul. Hutnicza 30, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1322141514;
update public.fields set name = 'Boisko do koszykówki · ul. Aleksandra Dulina 3, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1323189664;
update public.fields set name = 'Boisko do koszykówki · ul. Podkarpacka 7b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1334377667;
update public.fields set name = 'Boisko do koszykówki · ul. Czarny Dwór 18/1, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1353967579;
update public.fields set name = 'Boisko do koszykówki · ul. Demptowska 46, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1355009998;
update public.fields set name = 'Boisko do koszykówki · ul. Morska 77, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1363463489;
update public.fields set name = 'Boisko do koszykówki · ul. Daniela Chodowieckiego 4, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1364875932;
update public.fields set name = 'Boisko do koszykówki · ul. Aleksandra Dulina 3, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1368178106;
update public.fields set name = 'Boisko do koszykówki · ul. Orłowska 39, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1369808660;
update public.fields set name = 'Boisko do koszykówki · ul. Jana Kilińskiego 11a, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 1378897860;
update public.fields set name = 'Boisko do koszykówki · ul. Turkusowa 11, Rębiechowo', updated_at = now() where osm_type = 'way' and osm_id = 1380007954;
update public.fields set name = 'Boisko do koszykówki · ul. Złota 15, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1386601590;
update public.fields set name = 'Boisko do koszykówki · ul. Gniewska 22, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1392928402;
update public.fields set name = 'Boisko do koszykówki · ul. Zielona 53, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1396139092;
update public.fields set name = 'Boisko do koszykówki · ul. Generała Władysława Andersa 7, Rumia', updated_at = now() where osm_type = 'way' and osm_id = 1409230821;
update public.fields set name = 'Boisko do koszykówki · ul. Dąbrówki 102, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1412161810;
update public.fields set name = 'Boisko do koszykówki · ul. Aleja Legionów 44, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1421338450;
update public.fields set name = 'Boisko do koszykówki · ul. Marynarki Polskiej 142, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1424003846;
update public.fields set name = 'Boisko do koszykówki · ul. Myśliwskie Wzgórze 9, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1427253084;
update public.fields set name = 'Boisko do koszykówki · ul. Gwiazda Morza 25, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1434310807;
update public.fields set name = 'Boisko do koszykówki · ul. Raduńska 12, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1443008150;
update public.fields set name = 'Boisko do koszykówki · ul. Dedala 8, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1446546853;
update public.fields set name = 'Boisko do koszykówki · ul. Kaszubska 29, Pierwoszyno', updated_at = now() where osm_type = 'way' and osm_id = 1447192026;
update public.fields set name = 'Boisko do koszykówki · ul. Bydgoska 6, Rumia', updated_at = now() where osm_type = 'way' and osm_id = 1454604764;
update public.fields set name = 'Boisko do koszykówki · ul. Gostyńska 85b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1464948279;
update public.fields set name = 'Boisko do koszykówki · ul. Ignacego Krasickiego 10a, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1482864475;
update public.fields set name = 'Boisko do koszykówki · ul. Kapitańska 31, Gdynia', updated_at = now() where osm_type = 'way' and osm_id = 1483914931;
update public.fields set name = 'Boisko do koszykówki · ul. Mikołaja Reja 1, Sopot', updated_at = now() where osm_type = 'way' and osm_id = 1493104169;
update public.fields set name = 'Boisko do koszykówki · ul. Gdańskiego Kolejarza 37, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1498755403;
update public.fields set name = 'Boisko do koszykówki · ul. Sztormowa 7g, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1500094356;
update public.fields set name = 'Boisko do koszykówki · ul. Junacka 3, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1517793113;
update public.fields set name = 'Boisko do koszykówki · ul. Żywiecka 1b, Gdańsk', updated_at = now() where osm_type = 'way' and osm_id = 1528764563;

notify pgrst, 'reload schema';
